import mongoose from "mongoose";

const postSchema = new mongoose.Schema(
    {
        user: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true,
        },
        title: {
            type: String,
            required: [true, "Post title is required"],
            trim: true,
        },
        description: {
            type: String,
            required: [true, "Post description is required"],
            trim: true,
        },
        aiDescription: {
            type: String, // generated by AI
        },
        hashtags: {
            type: [String], // generated by AI
            default: [],
        },
        price: {
            type: Number,
            required: [true, "Price is required"],
            min: [0, "Price cannot be negative"],
        },
        category: {
            type: String,
            required: [true, "Category is required"],
        },
        subCategory: {
            type: String,
            required: [true, "Sub-category is required"],
        },
        mediaUrl: {
            type: String, // image/video URL (Cloudinary or local)
            required: false,
        },
        mediaType: {
            type: String,
            enum: ["image", "video", "text"],
            default: "text",
        },
        promoImageUrl: {
            type: String, // AI-generated promotional banner
        },
        sharedTo: {
            type: [String], // e.g. ["facebook", "whatsapp"]
            default: [],
        },
        expiryAt: {
            type: String,
            default: null,
        },
    },
    { timestamps: true }
);

const Post = mongoose.model("Post", postSchema);
export default Post;
